
local lu = require 'luaunit'
local tidy = require 'non-layered-tidy-trees'

function test_simple ()

    local tree = tidy.trees {

        [1] = {w = 70, h = 30, c = {2, 3, 4, 8}},
        [2] = {w = 10, h = 50, c = {}},
        [3] = {w = 20, h = 30, c = {}},
        [4] = {w = 30, h = 30, c = {5, 7}},
        [5] = {w = 20, h = 50, c = {6}},
        [6] = {w = 40, h = 10, c = {}},
        [7] = {w = 20, h = 20, c = {}},
        [8] = {w = 30, h = 50, c = {9, 10}},
        [9] = {w = 30, h = 20, c = {}},
        [10] = {w = 10, h = 10, c = {}},

    }
    
    local root = tree[-1]

    tidy.layout (root, true)

    local result = {}

    for k, t in pairs (tree) do

        local tbl = tidy.dbind (t)

        lu.assertEquals (k, tbl.id)
        result[k] = tbl

    end

    tidy.free(root);

    lu.assertEquals (result, {
        [-10]={
            c={10},
            change=0.0,
            cs=1,
            el=10,
            er=9,
            h=1.0,
            id=-10,
            mod=30.0,
            msel=30.0,
            mser=0.0,
            p=8,
            prelim=5.0,
            shift=0.0,
            w=0.0,
            x=90.0,
            y=82.0
        },
        [-9]={
            c={9},
            change=0.0,
            cs=1,
            el=9,
            er=9,
            h=1.0,
            id=-9,
            mod=0.0,
            msel=0.0,
            mser=0.0,
            p=8,
            prelim=15.0,
            shift=0.0,
            w=0.0,
            x=70.0,
            y=82.0
        },
        [-8]={
            c={8},
            change=0.0,
            cs=1,
            el=9,
            er=6,
            h=1.0,
            id=-8,
            mod=55.0,
            msel=55.0,
            mser=15.0,
            p=1,
            prelim=25.0,
            shift=0.0,
            w=0.0,
            x=80.0,
            y=31.0
        },
        [-7]={
            c={7},
            change=0.0,
            cs=1,
            el=7,
            er=6,
            h=1.0,
            id=-7,
            mod=30.0,
            msel=30.0,
            mser=0.0,
            p=4,
            prelim=10.0,
            shift=0.0,
            w=0.0,
            x=55.0,
            y=62.0
        },
        [-6]={
            c={6},
            change=0.0,
            cs=1,
            el=6,
            er=6,
            h=1.0,
            id=-6,
            mod=0.0,
            msel=0.0,
            mser=0.0,
            p=5,
            prelim=20.0,
            shift=0.0,
            w=0.0,
            x=35.0,
            y=113.0
        },
        [-5]={
            c={5},
            change=0.0,
            cs=1,
            el=6,
            er=6,
            h=1.0,
            id=-5,
            mod=0.0,
            msel=0.0,
            mser=0.0,
            p=4,
            prelim=20.0,
            shift=0.0,
            w=0.0,
            x=35.0,
            y=62.0
        },
        [-4]={
            c={4},
            change=0.0,
            cs=1,
            el=6,
            er=6,
            h=1.0,
            id=-4,
            mod=15.0,
            msel=15.0,
            mser=15.0,
            p=1,
            prelim=30.0,
            shift=0.0,
            w=0.0,
            x=45.0,
            y=31.0
        },
        [-3]={
            c={3},
            change=0.0,
            cs=1,
            el=3,
            er=2,
            h=1.0,
            id=-3,
            mod=10.0,
            msel=10.0,
            mser=0.0,
            p=1,
            prelim=10.0,
            shift=0.0,
            w=0.0,
            x=20.0,
            y=31.0
        },
        [-2]={
            c={2},
            change=0.0,
            cs=1,
            el=6,
            er=2,
            h=1.0,
            id=-2,
            mod=0.0,
            msel=15.0,
            mser=0.0,
            p=1,
            prelim=5.0,
            shift=0.0,
            w=0.0,
            x=5.0,
            y=31.0
        },
        [-1]={
            c={1},
            change=0.0,
            cs=1,
            el=6,
            er=6,
            h=1.0,
            id=-1,
            mod=0.0,
            msel=15.0,
            mser=15.0,
            prelim=42.5,
            shift=0.0,
            w=0.0,
            x=42.5,
            y=0.0
        },
        {
            c={-2, -3, -4, -8},
            change=0.0,
            cs=4,
            el=6,
            er=6,
            h=30.0,
            id=1,
            mod=0.0,
            msel=15.0,
            mser=15.0,
            p=-1,
            prelim=7.5,
            shift=0.0,
            w=70.0,
            x=7.5,
            y=1.0
        },
        {
            c={},
            change=0.0,
            cs=0,
            el=2,
            er=2,
            h=50.0,
            id=2,
            mod=15.0,
            msel=0.0,
            mser=0.0,
            p=-2,
            prelim=-15.0,
            shift=0.0,
            tl=5,
            w=10.0,
            x=0.0,
            y=32.0
        },
        {
            c={},
            change=0.0,
            cs=0,
            el=3,
            er=3,
            h=30.0,
            id=3,
            mod=-10.0,
            msel=0.0,
            mser=0.0,
            p=-3,
            prelim=10.0,
            shift=0.0,
            tr=2,
            w=20.0,
            x=10.0,
            y=32.0
        },
        {
            c={-5, -7},
            change=0.0,
            cs=2,
            el=6,
            er=6,
            h=30.0,
            id=4,
            mod=0.0,
            msel=0.0,
            mser=0.0,
            p=-4,
            prelim=15.0,
            shift=0.0,
            w=30.0,
            x=30.0,
            y=32.0
        },
        {
            c={-6},
            change=0.0,
            cs=1,
            el=6,
            er=6,
            h=50.0,
            id=5,
            mod=0.0,
            msel=0.0,
            mser=0.0,
            p=-5,
            prelim=10.0,
            shift=0.0,
            w=20.0,
            x=25.0,
            y=63.0
        },
        {
            c={},
            change=0.0,
            cs=0,
            el=6,
            er=6,
            h=10.0,
            id=6,
            mod=0.0,
            msel=0.0,
            mser=0.0,
            p=-6,
            prelim=0.0,
            shift=0.0,
            w=40.0,
            x=15.0,
            y=114.0
        },
        {
            c={},
            change=0.0,
            cs=0,
            el=7,
            er=7,
            h=20.0,
            id=7,
            mod=-30.0,
            msel=0.0,
            mser=0.0,
            p=-7,
            prelim=30.0,
            shift=0.0,
            tr=5,
            w=20.0,
            x=45.0,
            y=63.0
        },
        {
            c={-9, -10},
            change=0.0,
            cs=2,
            el=9,
            er=9,
            h=50.0,
            id=8,
            mod=0.0,
            msel=0.0,
            mser=0.0,
            p=-8,
            prelim=10.0,
            shift=0.0,
            w=30.0,
            x=65.0,
            y=32.0
        },
        {
            c={},
            change=0.0,
            cs=0,
            el=9,
            er=9,
            h=20.0,
            id=9,
            mod=-40.0,
            msel=0.0,
            mser=0.0,
            p=-9,
            prelim=40.0,
            shift=0.0,
            tr=5,
            w=30.0,
            x=55.0,
            y=83.0
        },
        {
            c={},
            change=0.0,
            cs=0,
            el=10,
            er=10,
            h=10.0,
            id=10,
            mod=-30.0,
            msel=0.0,
            mser=0.0,
            p=-10,
            prelim=30.0,
            shift=0.0,
            tr=9,
            w=10.0,
            x=85.0,
            y=83.0
        }
    }
    )



end

os.exit( lu.LuaUnit.run() )
